config/routes.rb
Rails.application.routes.draw do

  
  get 'hello_world/index'
  root 'books#index'

  resources :books
  resources :books do
    member do
      get :delete
    end
  end

  #get 'books/index'
  #get 'books/show'
  #get 'books/new'
  #get 'books/edit'
  #get 'books/delete'
  #get 'demo/index'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
    validates_presence_of :title
end

app/models/dateform.rb
class Dateform < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.order('title ASC')
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to(books_path)
    else 
      render('new')
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    if @book.update(book_params)
      redirect_to(books_path(@book))
    else 
      render('edit')
    end
  end

  def delete
    @book = Book.find(params[:id])
  end

  def destroy
    @book = Book.find(params[:id])
    @book.destroy
    redirect_to(books_path)
  end

  private
    def book_params
      params.require(:book).permit(:title, :author, :genre, :price, :published)
    end

end

app/controllers/demo_controller.rb
class DemoController < ApplicationController
  
  layout false

  def index
  end
end

app/controllers/hello_world_controller.rb
class HelloWorldController < ApplicationController
  def index
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[ show edit update destroy ]

  # GET /posts or /posts.json
  def index
    @posts = Post.all
  end

  # GET /posts/1 or /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts or /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: "Post was successfully created." }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1 or /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: "Post was successfully updated." }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1 or /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: "Post was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/demo_helper.rb
module DemoHelper
end

app/helpers/hello_world_helper.rb
module HelloWorldHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/books/delete.html.erb
<div class="delete">
    <%= link_to("Go Back", books_path, :class=>'back-link')%>

    <h1>Delete Phrase</h1>
    <!-- HTML based on tutorials by Kevin Skoglund on LinkedInLearning "Ruby on Rails 6 Essential Training"-->
    

    <%= form_for(@book, :method => 'delete') do |f| %>

    <p>Confirm deletion of <%= @book.title%></p>
    

    <div class="form-buttons">
      <%= f.submit("Confirm") %>
    </div>
    <% end %>
    <div class="form-buttons">
      <%= link_to("CANCEL DELETION", books_path, :class=>'back-link')%>
    </div>
</div>

app/views/books/edit.html.erb
<div class="edit">
    <%= link_to("Go Back", books_path, :class=>'back-link')%>

    <h1>Edit existing phrase</h1>
    <!-- HTML based on tutorials by Kevin Skoglund on LinkedInLearning "Ruby on Rails 6 Essential Training"-->
    
    <%= form_for(@book) do |f| %>

    <table summary="Phrase form fields">
      <tr>
        <th><%= f.label :title, 'Phrase'%></th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th><%= f.label :author, 'Desc (opt)'%></th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th><%= f.label :genre, 'Color'%></th>
        <td><%= f.select :genre, options_for_select([["Blue"],["Green"],["Red"],["Yellow"],["Gray"]]) %></td>
      </tr>
     
    </table>

    <div class="form-buttons">
      <%= f.submit("Update phrase") %>
    </div>
    <% end %>
</div>

app/views/books/index.html.erb
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
<style>

/* The heart of the matter */
.btn-matrix > .btn:nth-child(3n+4) {
  clear: left;
  margin-left: 0;
}
.btn-matrix > .btn:nth-child(n+4) {
  margin-top: -1px;
}
.btn-matrix > .btn:first-child {
  border-bottom-left-radius: 0;
}
.btn-matrix > .btn:nth-child(3) {
  border-top-right-radius: 4px !important;
}
.btn-matrix > .btn:nth-last-child(3) {
  border-bottom-left-radius: 4px !important;
}
.btn-matrix > .btn:last-child {
  border-top-right-radius: 0;
}

/* Decorations */
.btn-matrix {
  margin: 20px;
}


</style>


<script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>


<div class ="books">
    
    
    <!-- HTML based on tutorials by Kevin Skoglund on LinkedInLearning "Ruby on Rails 6 Essential Training"-->
    <!-- Table template from Faiz Ahmed https://codepen.io/faaezahmd/pen/dJeRex-->
    <div class="container">
    <h2>TalkBuddy</h2>
    <%= link_to("Add a phrase.", new_book_path, :class=> 'action new btn btn-lg btn-success')%>
    <br>

        <div class="btn-group btn-matrix" id="new">
            <% @books.each do |book| %>
                <script type="text/javascript">
                    function pageLoad(e){
                        var btn2BAdded = document.createElement("input");
                        btn2BAdded.type = "button";
                        btn2BAdded.className += 'btn btn-lg btn-block';
                        btn2BAdded.className += "<%= book.genre == "Blue" ? ' btn-primary' : ''%>";
                        btn2BAdded.className += "<%= book.genre == "Green" ? ' btn-success' : ''%>";
                        btn2BAdded.className += "<%= book.genre == "Yellow" ? ' btn-warning' : ''%>";
                        btn2BAdded.className += "<%= book.genre == "Red" ? ' btn-danger' : ''%>";

                        var textTyped = "<%= book.title %>";
                        btn2BAdded.value = textTyped;
                        btn2BAdded.id = "btn_rv";
                        var element = document.getElementById("new");
                        element.appendChild(btn2BAdded);
                        btn2BAdded.addEventListener('click', function(){
                            var dialog = new SpeechSynthesisUtterance(textTyped);
                            speechSynthesis.speak(dialog);
                        }, false);
                            
                    };
                     
                </script>

               <script type="text/javascript">
                
                    pageLoad();
                
                </script>

                <!--<button type="button" class="btn btn-lg btn-default" data-toggle="tooltip" data-placement="top" title="<%= book.author %>"><%= book.title %></button>-->
            <%end%>
        </div>

        <br><br><br><br><br><br><br><br><br><br><br>
       
    
        <ul class="responsive-table">
        
            <li class="table-header">
            <div class="col col-1">Phrase</div>
            <div class="col col-2">Description</div>
            <div class="col col-3">Actions</div>
            </li>
            <% @books.each do |book| %>
                <li class="table-row">
                    <div class="col col-1" data-label="Title"><%= book.title %></div>
                    <div class="col col-2" data-label="Author"><%= book.author %></div>
                    <div class="col col-3" data-label="Actions"> 
                        <%= link_to("Edit", edit_book_path(book), :class => 'action edit action new btn btn-warning') %>
                        <%= link_to("Delete", delete_book_path(book), :class => 'action delete btn btn-danger') %>
                        </div>
                </li>
            <%end%>
        </ul>
         
    </div>
</div>
    

app/views/books/new.html.erb
<div class="new">
    <%= link_to("Go Back", books_path, :class=>'back-link')%>

    <h1>Add a new phrase.</h1>
    <!-- HTML based on tutorials by Kevin Skoglund on LinkedInLearning "Ruby on Rails 6 Essential Training"-->
    
    <%= form_for(@book, :url => books_path, :method => 'post') do |f| %>

    <table summary="Phrase form fields">
      <tr>
        <th><%= f.label :title, 'Phrase'%></th>
        <td><%= f.text_field(:title) %></td>
      </tr>
      <tr>
        <th><%= f.label :author, 'Desc (opt)'%></th>
        <td><%= f.text_field(:author) %></td>
      </tr>
      <tr>
        <th><%= f.label :genre, 'Color'%></th>
        <td><%= f.select :genre, options_for_select([["Blue"],["Green"],["Red"],["Yellow"],["Gray"]]) %></td>
      </tr>
     
    </table>


    <div class="form-buttons">
      <%= f.submit("Create phrase") %>
    </div>
    <% end %>
</div>

app/views/books/show.html.erb
<div class="show">
<!-- HTML based on tutorials by Kevin Skoglund on LinkedInLearning "Ruby on Rails 6 Essential Training"-->

    <%= link_to("Go Back", books_path, :class=>'back-link')%>
    <h1>Books</h1>
    <br>

    <table>
        <tr>
            <th>ID</th>
            <td><%= @book.id %></td> 
        </tr>
        <tr>
            <th>Title</th>
            <td><%= @book.title %></td> 
        </tr>
        <tr>
            <th>Author</th>
            <td><%= @book.author %></td> 
        </tr>
        <tr>
            <th>Genre</th>
            <td><%= @book.genre %></td> 
        </tr>
        <tr>
            <th>Price</th>
            <td><%= @book.price %></td> 
        </tr>
        <tr>
            <th>Published</th>
            <td><%= @book.published %></td> 
        </tr>
        <tr>
            <th>Entry Created</th>
            <td><%= @book.created_at %></td> 
        </tr>
        <tr>
            <th>Last Edit</th>
            <td><%= @book.updated_at %></td> 
        </tr>
    </table>

</div>

app/views/demo/index.html.erb
<h1>Hello World</h1>
<p>HIHIHIHIFind me in app/views/demo/index.html.erb</p>

<br>
<%= link_to("All Books", books_path)%>

app/views/hello_world/index.html.erb
<h1>HelloWorld#index</h1>

<h2>
Hello, world!
</h2>


<p>Find me in app/views/hello_world/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Demo</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.title %></td>
        <td><%= post.body %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Post', new_post_path %>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form', post: @post %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @post.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @post.body %>
</p>

<%= link_to 'Edit', edit_post_path(@post) %> |
<%= link_to 'Back', posts_path %>